/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parq;

import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.JOptionPane;

/**
 *
 * @author Miguel Moreno
 */
public class salida extends javax.swing.JFrame {

    Vehiculo objVe;

    /**
     * Creates new form salida
     */
    public salida(Vehiculo objV) {
        initComponents();
        lblPlaca.setText(objV.placa);
        lblPropietario.setText(objV.propietario);
        String tipo = "";
        switch (objV.tipo) {
            case 1:
                tipo = "Bicicleta";
                break;
            case 2:
                tipo = "Motocicleta";
                break;
            case 3:
                tipo = "Automovil";
                break;
        }
        txtTarifaB.setText("$" + objV.VALOR1);
        txtTarifaA.setText("$" + objV.VALOR3);
        txtTarifaM.setText("$" + objV.VALOR2);
        lblTipo.setText(tipo);
        objVe = objV;
        btnCal.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPropietario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMesS = new javax.swing.JTextField();
        txtHoraS = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDiaS = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMinS = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAñoS = new javax.swing.JTextField();
        btnRegistrarS = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTarifaB = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTarifaM = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTarifaA = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnCal = new javax.swing.JButton();
        bntSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Placa");

        lblPlaca.setText("\"\"");

        jLabel3.setText("Propietario");

        lblPropietario.setText("\"\"");

        jLabel4.setText("Tipo");

        lblTipo.setText("\"\"");

        jLabel5.setText("Mes Salida");

        jLabel6.setText("Hora Salida");

        jLabel7.setText("Dia Salida");

        jLabel13.setText("Min Salida");

        jLabel8.setText("Año Salida");

        btnRegistrarS.setText("Registrar salida");
        btnRegistrarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarSActionPerformed(evt);
            }
        });

        jLabel2.setText("Bicicleta");

        txtTarifaB.setText("\"\"");

        jLabel9.setText("Motocicleta");

        txtTarifaM.setText("\"\"");

        jLabel10.setText("Automovil");

        txtTarifaA.setText("\"\"");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Tarifas");

        btnCal.setText("Calcular");
        btnCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalActionPerformed(evt);
            }
        });

        bntSalir.setText("Salir");
        bntSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(42, 42, 42)
                                    .addComponent(lblPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTarifaM, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(42, 42, 42)
                                    .addComponent(txtTarifaB, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTarifaA, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel13)
                            .addComponent(btnRegistrarS))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAñoS, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDiaS, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMinS, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCal))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMesS, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHoraS, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(bntSalir))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblPlaca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblPropietario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblTipo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTarifaB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtTarifaM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtTarifaA))))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtAñoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMesS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtHoraS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtDiaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtMinS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarS)
                    .addComponent(btnCal)
                    .addComponent(bntSalir))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarSActionPerformed
        if (validarS()) {
            int añoS = Integer.parseInt(txtAñoS.getText());
            int mesS = Integer.parseInt(txtMesS.getText());
            int diaS = Integer.parseInt(txtDiaS.getText());
            int horaS = Integer.parseInt(txtHoraS.getText());
            int minS = Integer.parseInt(txtMinS.getText());

            objVe.registrarSalida(añoS, mesS, diaS, horaS, minS);

            btnCal.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Ha registrado la salida correctamente!");
        }


    }//GEN-LAST:event_btnRegistrarSActionPerformed

    private void btnCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalActionPerformed
        objVe.calcularTiempo();
        objVe.calcularValor();
        NumberFormat fMoneda = NumberFormat.getCurrencyInstance();
        JOptionPane.showMessageDialog(null, "El valor a pagar es: " + fMoneda.format(objVe.totValor) + " pesos por " + objVe.totMin + " minutos");
    }//GEN-LAST:event_btnCalActionPerformed

    private void bntSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_bntSalirActionPerformed

    private boolean validarS() {

        if (txtAñoS.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tiene que llenar el campo Año de continuar!");
            txtAñoS.requestFocus();
            return false;
        }
        if (Integer.parseInt(txtAñoS.getText()) < objVe.aE) {
            JOptionPane.showMessageDialog(null, "El año de salida no puede ser menor al año de entrada  " + objVe.aE + "!");
            txtAñoS.requestFocus();
            return false;
        }
        if (txtMesS.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tiene que llenar el campo Mes antes de continuar!");
            txtMesS.requestFocus();
            return false;
        }
        if (Integer.parseInt(txtMesS.getText()) > 12) {
            JOptionPane.showMessageDialog(null, "Mes invalido!");
            txtMesS.requestFocus();
            return false;
        }
        if (Integer.parseInt(txtMesS.getText()) < objVe.mE && Integer.parseInt(txtAñoS.getText()) == objVe.aE) {
            JOptionPane.showMessageDialog(null, "El mes es menor al mes de entrada " + objVe.mE + "!");
            txtMesS.requestFocus();
            return false;
        }
        if (txtDiaS.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tiene que llenar el campo Dia antes de continuar!");
            txtDiaS.requestFocus();
            return false;
        }
        if (Integer.parseInt(txtDiaS.getText()) > 31) {
            JOptionPane.showMessageDialog(null, "Dia invalido!");
            txtDiaS.requestFocus();
            return false;
        }
        if (Integer.parseInt(txtDiaS.getText()) < objVe.dE && Integer.parseInt(txtMesS.getText()) == objVe.mE) {
            JOptionPane.showMessageDialog(null, "El dia es menor al dia de entrada " + objVe.dE + "!");
            txtDiaS.requestFocus();
            return false;
        }
        if (txtHoraS.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tiene que llenar el campo Hora antes de continuar!");
            txtHoraS.requestFocus();
            return false;
        }
        if (Integer.parseInt(txtHoraS.getText()) > 23) {
            JOptionPane.showMessageDialog(null, "La hora es invalida!");
            txtHoraS.requestFocus();
            return false;
        }
        if (Integer.parseInt(txtHoraS.getText()) < objVe.hE && Integer.parseInt(txtDiaS.getText()) == objVe.dE) {
            JOptionPane.showMessageDialog(null, "La hora es menor a la hora de entrada " + objVe.hE + "!");
            txtHoraS.requestFocus();
            return false;
        }

        if (txtMinS.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tiene que llenar el campo Minutos antes de continuar!");
            txtMinS.requestFocus();
            return false;
        }
        if (Integer.parseInt(txtMinS.getText()) > 59) {
            JOptionPane.showMessageDialog(null, "El minuto es menor al minuto de entrada  " + objVe.minE + "!");
            txtMinS.requestFocus();
            return false;
        }
        if ((Integer.parseInt(txtMinS.getText()) < objVe.minE) && (Integer.parseInt(txtHoraS.getText()) == objVe.hE)) {
            JOptionPane.showMessageDialog(null, "El minuto es menor al minuto de entrada  " + objVe.minE + "!");
            txtMinS.requestFocus();
            return false;
        }
        return true;

    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSalir;
    private javax.swing.JButton btnCal;
    private javax.swing.JButton btnRegistrarS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblPropietario;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTextField txtAñoS;
    private javax.swing.JTextField txtDiaS;
    private javax.swing.JTextField txtHoraS;
    private javax.swing.JTextField txtMesS;
    private javax.swing.JTextField txtMinS;
    private javax.swing.JLabel txtTarifaA;
    private javax.swing.JLabel txtTarifaB;
    private javax.swing.JLabel txtTarifaM;
    // End of variables declaration//GEN-END:variables
}
